package:
  name: sift4g
  version: "2.0.0"

source:
  url: http://sift.bii.a-star.edu.sg/sift4g/SIFT4G_v2.0.0.tar.gz
  sha256: 51e8f358062d28e22592f8f77545143f4b0671ba3b8b50be63c790c672108908
  # conda-build/conda/requests decompresses the source during download due to erroneous server response.
  # ref: https://github.com/conda/conda-build/issues/3799
  # If the server changes its behavior, below is the alt url and the original checksum:
  #url: https://depot.galaxyproject.org/software/sift4g/sift4g_2.0.0_src_all.tar.gz
  #sha256: c55c0690cc6437eb6c726be3390d5368a2145bda726130d8a6b0c2faaf4152fb
  patches:
    - 0001-Remove-superfluous-use-of-non-imported-function.patch

build:
  number: 2
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - sift4g -h 2>&1 | grep -qF "sift4g"

about:
  home: http://sift.bii.a-star.edu.sg/sift4g/
  license: GPL-3.0
  summary: 'SIFT 4G is a faster version of SIFT that enables us to scale up and provide SIFT predictions for more organisms.'
