package:
  name: gecode
  version: "5.0.0"

source:
  url: https://github.com/Gecode/gecode/archive/release-5.0.0.tar.gz
  sha256: 1f1063ff0116cde1a1e0dde47c1328dcf5d92ef0ea8f38d3ad8e7d4c97b4020e

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - perl
    - mpfr
    - gmp
  run:
    - mpfr
    - gmp

test:
  commands:
    - fzn-gecode --help >& /dev/null
    - magic-sequence --help >& /dev/null

about:
  home: http://www.gecode.org/
  license: MIT
  license_file: LICENSE
  summary: Generic constraint development environment
