{% set name = "WiggleTools" %}
{% set version = "1.2.4" %}
{% set sha256 = "3d21a107321aa0ab6c96a2dae585a61e8dfca566a8c18e15b677c05b3ec64ead" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/Ensembl/WiggleTools/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libbigwig
    - htslib
    - gsl
    - libcblas
  run:
    - libbigwig
    - htslib
    - gsl
    - libcblas

test:
  commands:
    - wiggletools --help

about:
  home: https://github.com/Ensembl/WiggleTools
  license: Apache
  license_family: Apache
  license_file: LICENSE.txt
  summary: The WiggleTools package allows genomewide data files to be manipulated as numerical functions,
           equipped with all the standard functional analysis operators (sum, product, product by a scalar, comparators),
           and derived statistics (mean, median, variance, stddev, t-test, Wilcoxon's rank sum test, etc).
