{% set name = "octopus" %}
{% set version = "0.6.3b" %}
{% set sha256 = "46e3d8ecc737e98a00aa66eefd663edb2b606873839b898210a4369311c12c67" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1
  # Clang compilation issue:
  #   .../algorithm:2523:5: error: static_assert failed due to requirement '__is_cpp17_forward_iterator<...> >::value' "std::min_element requires a ForwardIterator"
  #         static_assert(__is_cpp17_forward_iterator<_ForwardIterator>::value,
  #   .../src/core/tools/hapgen/haplotype_tree.cpp:290:33: note: in ... (lambda at .../src/core/tools/hapgen/haplotype_tree.cpp:291:45)>' requested here
  skip: True  # [osx]

source:
  url: https://github.com/luntergroup/{{ name }}/archive/v0.6.3-beta.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - gmp
    - htslib
    - wget
    - icu
    - bzip2
    - xz
    - zlib
  run:
    - boost-cpp
    - gmp
    - htslib
    - icu
    - bzip2
    - xz
    - zlib

test:
  commands:
    - octopus -h

about:
  home: https://github.com/luntergroup/octopus
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Octopus is a mapping-based variant caller that implements several calling models within a unified haplotype-aware framework."
