{% set name = "nimnexus" %}
{% set version = "0.1.1" %}
{% set revision = "f99eaf1" %}
{% set sha256hash = "620a85f688ab2b431629a4f716f652e5c6e1ff2dd30fab74c44039f18305fbb9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/avsecz/{{ name }}/archive/{{ revision }}.tar.gz
    sha256: {{ sha256hash }}
  - url: https://github.com/nim-lang/Nim/archive/v0.19.0.tar.gz
    sha256: f6a0b1c7bc227db1f7b8efa3bde0c6f23903c9184beebc99ff0094378c28e1ee
    folder: nim
  - url: https://github.com/nim-lang/csources/archive/v0.19.0.tar.gz
    sha256: 68042afae0b24915acac813b52b9ee0a303219e990d3bfa05ca57fb6bbc51578
    folder: nim/csources
  - url: https://github.com/nim-lang/nimble/archive/v0.9.0.tar.gz
    sha256: d02cc0b1787fa30e6d88a1ee7aa067c1555b7763d2716742d1d10132df550456
    folder: nimble
  # The version (0.2.7) of hts-nim is more or less arbitrarily chosen;
  # it was the latest release when the previous build happened.
  - url: https://github.com/brentp/hts-nim/archive/v0.2.7.tar.gz
    sha256: 3c9a81eaedb898642c04a14104ccff108104c328b361f7032778194ea9c99f33
    folder: hts-nim



build:
  number: 1
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pcre
    - htslib
  run:
    - pcre
    - htslib

test:
  commands:
    - nimnexus trim -h
    - nimnexus dedup -h
    
about:
  home: https://github.com/avsecz/nimnexus
  license: MIT
  summary: command-line tools for processing ChIP-nexus data
