{% set name = "inStrain" %}
{% set version = "1.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ef2911aae25e67dd75e2cab20c61673a0e6654ad4bfd041ed203c9e418cbfb50

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - biopython
    - drep
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pandas >=0.25
    - psutil
    - pysam
    - pytest
    - python >=3.4
    - scikit-learn
    - seaborn
    - tqdm
    - numba
    - lmfit

test:
  imports:
    - inStrain
  commands:
    - inStrain profile --help
    - inStrain compare --help

about:
  home: "https://github.com/MrOlm/inStrain"
  license: MIT
  license_family: MIT
  summary: "Calculation of strain-level metrics"
