package:
  name: epa-ng
  version: "0.3.7"

build:
  number: 0

source:
  url: https://github.com/Pbdas/epa-ng/archive/v0.3.7.tar.gz
  sha256: 780f031aa5edb256eb5604d76d0c6cee067de205ae32534d7c61f3a30b5e4c67

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - flex
    - bison
    - m4
    - cmake
    - automake
    - autoconf
    - llvm-openmp # [osx]
  host:
    - zlib
    - llvm-openmp # [osx]
  run:
    - zlib
    - llvm-openmp # [osx]
test:
  commands:
    - epa-ng -h | grep "Number of threads to use" > /dev/null
about:
  home: https://github.com/Pbdas/epa-ng
  license: GNU Affero General Public License v3.0
  license_file: LICENSE
  summary: Massively parallel phylogenetic placement of genetic sequences

extra:
  identifiers:
    - doi:10.1093/sysbio/syy054
