package:
  name: hgtools
  version: "8.2.0"

source:
  url: https://files.pythonhosted.org/packages/83/e8/fc576b4a1664d1f170a8251f2774dcad9d577a3cd631c9185b7ed3675159/hgtools-8.2.0.tar.gz
  sha256: 5f30e3e7729f67e414b63ae91697743bb2ec72f3cac0c514d16fd3c21bd25300

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - backports.unittest_mock

test:
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests

  requires:
    - backports.unittest_mock
    - pytest >=2.8

about:
  home: https://github.com/jaraco/hgtools
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial and Git repositories'
