{% set version = "0.6.17" %}

package:
  name: pyfastx
  version: {{ version }}

source:
  url: https://github.com/lmdu/pyfastx/archive/{{ version }}.tar.gz
  sha256: 26ff643ac2a96c5a3df2cc23e550e6fb6febee1fe198966caa077c255542a0d9


build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py2k]
  entry_points:
    - pyfastx = pyfastxcli:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - zlib
    - pip
  run:
    - zlib
    - python

test:
  imports:
    - pyfastx
  commands:
    - pyfastx --help

about:
  home: https://github.com/lmdu/pyfastx
  license: MIT
  license_file: LICENSE
  summary:  |
          pyfastx is a python module for fast random
          access to sequences from plain and gzipped
          FASTA/Q file
