package:
  name: metasv
  version: '0.5.4'
source:
  url: https://github.com/bioinform/metasv/archive/0.5.4.tar.gz
  md5: de2e21ac4f86bc4d1830bdfff95d8391

build:
  number: 2
  skip: True # [py>30]
  script: |
    sed -i.bak '/install_requires=/{s/"cython", //}' setup.py
    {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python
    - pybedtools ==0.6.9
    - pyvcf ==0.6.7
    - pysam ==0.7.7
    - age-metasv
    - spades

test:
  commands:
    - run_metasv.py -h

about:
  home: https://github.com/bioinform/metasv
  summary: An accurate and integrative structural-variant caller for next generation sequencing
  license: MIT
