{% set version = "1.7.0" %}

package:
  name: tandem-genotypes
  version: {{ version }}

source:
  url: https://github.com/mcfrith/tandem-genotypes/archive/{{ version }}.tar.gz
  sha256: fb3ef4a71a60a1cb90c87788c5844339ab67246c46c6d9bd8804217b88e2f9a0

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - r-base

test:
  commands:
    - tandem-genotypes --help
    - tandem-genotypes-join --help
    - tandem-genotypes-plot --help

about:
  home: https://github.com/mcfrith/tandem-genotypes
  summary: Find tandem repeat length changes, from "long" DNA reads aligned to a genome
  license: GPL-3.0-or-later
  license_file: LICENSE
