package:
  name: pronto
  version: "2.2.3"

source:
  url: https://files.pythonhosted.org/packages/4a/7d/1a455b261d71c0497a27c04f78fe2b67d621a2b6ba02a450e4f9bb0ce224/pronto-2.2.3.zip
  sha256: f5f094bd28d42ebe91c1bed88eb236b3179d59726fc81fb2708b7c64442c8d88

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - chardet >=3.0
    - fastobo >=0.8.2
    - networkx >=2.3
    - python-dateutil >=2.8
    - frozendict

test:
  imports:
    - pronto
    - pronto.logic
    - pronto.utils
    - pronto.parsers
    - pronto.serializers

about:
  home: http://github.com/althonos/pronto
  license: MIT
  summary: 'Python frontend to ontologies'
  license_family: MIT

extra:
  recipe-maintainers:
    - althonos

