{% set version = "0.2.5.5" %}

package:
  name: mimseq
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mimseq/mimseq-{{ version }}.tar.gz
  sha256: 3a79fc7fc934e6943ba1cbb368fe39de6d801a44e20a4b10e278c8a6c5a20159

build:
  number: 1
  noarch: python
  entry_points:
    - mimseq = mimseq.mimseq:main
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - r-base <3.7.0a0
    - biopython
    - matplotlib-base
    - numpy
    - pandas
    - pybedtools
    - pyfiglet
    - pysam
    - seaborn
    - pandas
    - infernal
    - blast
    - gmap 2019.02.26
    - samtools
    - bedtools
    - r-ggplot2 =3.2.1
    - bioconductor-complexheatmap
    - bioconductor-deseq2
    - r-pheatmap
    - r-calibrate
    - r-gridextra
    - r-plyr
    - r-dplyr
    - r-tidyverse
    - r-devtools

test:
  imports:
    - mimseq
  commands:
    - mimseq --help

about:
  home: "https://github.com/nedialkova-lab/mim-tRNAseq"
  license: GPL-3.0-only
  license_family: GPL3
  summary: "Modification-induced misincorporation tRNA sequencing."
