{% set name = "hts-nim-tools" %}
{% set version = "0.1.5" %}
{% set revision = "e4249bf" %}
{% set sha256hash = "d45468183f66497c6c5cc183e0fd363709844d6f474326411eb57c74ffa4a4c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/brentp/{{ name }}/archive/{{ revision }}.tar.gz
    sha256: {{ sha256hash }}
  - url: https://github.com/nim-lang/Nim/archive/v0.18.0.tar.gz
    sha256: 9b9982f349fb96db44020a6da14fa683179b637a3d94782e2c99156ac613e187
    folder: nim
  - url: https://github.com/nim-lang/csources/archive/v0.18.0.tar.gz
    sha256: e9aff9d58661ea852ae424ba34fc3750b45fb31982645a3038de2300bea2d17c
    folder: nim/csources
  - url: https://github.com/nim-lang/nimble/archive/v0.8.10.tar.gz
    sha256: bb1962a71448945775bba4c1fd63162fa9bb2afbaf6d6f61a5012c1c3fee59f9
    folder: nimble
  # The version (0.1.9) of hts-nim is more or less arbitrarily chosen;
  # it was the latest release when the previous build happened.
  - url: https://github.com/brentp/hts-nim/archive/v0.1.9.tar.gz
    sha256: b1989cc6e3636fc9e9d6c683b60aa60e441cb04d94e930d171dff6b859c61027
    folder: hts-nim

build:
  number: 3
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pcre
    - htslib
  run:
    - pcre
    - htslib

test:
  commands:
    - hts_nim_tools -h
    - hts_nim_tools count-reads -h

about:
  home: https://github.com/brentp/hts-nim-tools
  license: MIT
  summary: useful command-line tools written to show-case hts-nim
