{% set name = "pmx_biobb" %}
{% set version = "3.0.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14b2efb3ac7141128998dcb2a93e07eec95db4e4c0adadd65c3925884bd54734

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - future
    - matplotlib
    - numpy
    - python
    - scipy

  run:
    - python >=3.7
    - future
    - matplotlib
    - numpy
    - python
    - scipy

test:
  imports:
    - pmx
  commands:
    - pmx --help
  requires:
    - pytest

about:
  home: https://github.com/deGrootLab/pmx/tree/develop
  license: GNU General Public (GPL)
  license_family: LGPL
  summary: pmx is a python library that allows users to setup and analyse molecular dynamics simulations with the Gromacs package.
  description: "# pmx python 3 version\n\
    ## Warning\n\ 
    This is a development version of pmx, it is not stable or reliable yet. You are welcome to try/test it and provide feedback, but use at your own risk.\
    The current stable version of pmx can be found in the [master branch](https://github.com/deGrootLab/pmx).\
    \n\npmx is a python library that allows users to setup and analyse molecular dynamics simulations with the Gromacs package. Among its main features are the \
    setup and analysis of alchemical free energy calculations for protein, nucleic acid, and small molecule mutations.\
    \n\n[https://degrootlab.github.io/pmx/](https://degrootlab.github.io/pmx/)\
    \n\n## Citations\n\
    pmx is a research software. If you make use of it in scientific publications, please cite the following papers:\
    \n\n@article{Gapsys2015pmx,\n\
    title = {pmx: Automated protein structure and topology\n\
    generation for alchemical perturbations},\n\
    author = {Gapsys, Vytautas and Michielssens, Servaas\n\
    and Seeliger, Daniel and de Groot, Bert L.},\n\
    journal = {Journal of Computational Chemistry},\n\
    volume = {36},\n\
    number = {5},\n\
    pages = {348--354},\n\
    year = {2015},\n\
    doi = {10.1002/jcc.23804}\n\
    }\
    \n\n@article{Seeliger2010pmx,\n\
        title = {Protein Thermostability Calculations Using\n\
        Alchemical Free Energy Simulations},\n\
        author = {Seeliger, Daniel and de Groot, Bert L.},\n\
        journal = {Biophysical Journal},\n\
        volume = {98},\n\
        number = {10},\n\
        pages = {2309--2316},\n\
        year = {2010},\n\
        doi = {10.1016/j.bpj.2010.01.051}\n\
    }\
    \n\n## License\n\
    pmx is licensed under the GNU Lesser General Public License v3.0 (LGPL v3).\n\n\n"
