{% set name = "constax" %}
{% set version = "2.0.1" %}
{% set sha256hash = "462bcf618c20cd44e877e18027c7799c4f04bb2fe95f972fed6ad99a19f1bb46" %}
{% set md5hash = "9044f76d1c367e755c8125944a09656f" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

source:
  url: https://github.com/liberjul/CONSTAXv2/archive/v2.0.1.tar.gz
  sha256: {{ sha256hash }}
  md5: {{ md5hash }}

requirements:
  host:
  build:
    - python >=3.6
  run:
    - python >=3.6
    - rdptools
    - vsearch
    - blast
    - pandas
    - numpy

about:
  home: 'https://github.com/liberjul/CONSTAXv2'
  license: MIT

  summary: 'A software for accurate taxonomic classification of environmental DNA markers'
