{% set version = "13.8" %}
{% set date = "20200829" %}
{% set sha256 = "a3b7d05cacea3cce147c1bd559b18ff342dbec82025b9c7773a19badefe3a4cf" %}

package:
  name: entrez-direct
  version: {{ version }}

build:
  number: 0

source:
  url: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/{{ version }}.{{ date }}/edirect.tar.gz
  sha256: {{ sha256 }}
  patches:
    - xtract.patch

requirements:
  build:
    # The installer script downloads statically compiled binaries, so this is effectively just avoiding linter errors
    - {{ compiler('go') }}
  host:
    - perl
    - perl-html-parser
    - perl-html-tagset
    - perl-html-tree
    - perl-http-cookies
    - perl-http-date
    - perl-http-message
    - perl-http-negotiate
    - perl-io-socket-ssl
    - perl-lwp-mediatypes
    - perl-lwp-protocol-https
    - perl-net-http
    - perl-uri
    - perl-www-robotrules
    - perl-mozilla-ca
    - perl-xml-simple
  run:
    - perl
    - perl-html-parser
    - perl-html-tagset
    - perl-html-tree
    - perl-http-cookies
    - perl-http-date
    - perl-http-message
    - perl-http-negotiate
    - perl-io-socket-ssl
    - perl-lwp-mediatypes
    - perl-lwp-protocol-https
    - perl-net-http
    - perl-uri
    - perl-www-robotrules
    - perl-mozilla-ca
    - perl-xml-simple

test:
  commands:
    - efetch --help
    - epost --help
    - efilter --help
    - einfo --help
    - esearch --help
    - elink --help
    - espell --help
    - enotify --help
    - esummary --help
    - entrez-phrase-search --help
    - xtract -version

about:
  home: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/{{ version }}.{{ date }}/README
  license: PUBLIC DOMAIN
  summary: Entrez Direct (EDirect) is an advanced method for accessing the NCBI's set of interconnected databases (publication, sequence, structure, gene, variation, expression, etc.) from a UNIX terminal window. Functions take search terms from command-line arguments. Individual operations are combined to build multi-step queries. Record retrieval and formatting normally complete the process.
