{% set version="1.1.3" %}

package:
  name: covtobed
  version: {{ version }}

source:
  url: https://github.com/telatin/covtobed/archive/v{{ version }}.tar.gz
  sha256: 2543b8a2f52ab4aaab2e1bb60e0cd4bf4de90d6ba12db95c630e48ca0c198777

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - bamtools
    - zlib
  run:
    - bamtools
    - zlib

test:
  files:
    - test.bam
  commands:
    # (see run_test.sh for remainder of tests)
    - covtobed -h

about:
  home: https://github.com/telatin/covtobed/
  license: 'MIT'
  license_file: LICENSE
  summary: 'covtobed - generate a BED file of covered regions from a BAM file'
